language: ruby
rvm:
- 1.9.3
- 2.0.0
addons:
  code_climate:
    repo_token:
      secure: qtwSJZvJiazkLi2roWh+HTBj6PDYdWnREHvjlw84q+YLTP+nbpi0gnoYkEyfOzgJIC2vKNGztHpxutO0LtUpRfJI+3+hpY0cSRhvvWseQmDoyGs6TnnjdBzcK3Ldsfy/reUyjaTVz14a0hY6M0clB6j/Rqlo1KWaEfwSz52zsbU=
