language: ruby
rvm:
- 1.9.3
- 2.0.0
env:
  global:
  - secure: cN032ldTmY1faRq1joBzogNkNew7AB4TI3G4A4GloIWhn/yXrR1kDAOMqFJXXuXLP0YGN+gsWtVvEUD/mZOmucVAIydyexW0/Lq4qkS9oegk00fYSwjD18tQH8KVfuoho2UZ0h+Lu4SY+jG0WvYnA5L9fXQ+lnQDz6GscpwRzik=
  - secure: uZM+Vi26eA9bgz9BG4R6KKhU+P3ptb4/ObQ9XAu3lukjAm6adhR1EKWtUMR901vyFh9TK1a3ZbRNdzffSbCS1frfe5efhnl3XI2zIiQfz0CKOqMXgg+LYREBSHUdH5/QQDPiZ9yxRwCjHMuiWEHdmwuEataxJKp1Zn69GIFmcu8=
