language: ruby

rvm:
  - "1.9.3"
  - "2.0.0"

addons:
  code_climate:
    repo_token:
      secure: b4KsQ0c4zyb+hcNZWhEvOGXpYvc9+iBA50AUlUn10YNeLfdnbxYyASWWbIsPHP5dXf9Krp54tD293UHoi2+9BbcXIwyHuVwRMS8oNN66MQJi3PABCf9odGtCMkULCcLOp/yy7kszmwz9iBma6hWQk2Vn1alHv7NBXr4ir7RWBWg=
